FROM mdillon/postgis:9.5-alpine

COPY db_scripts/1-init-DDL.sql /docker-entrypoint-initdb.d/
COPY db_scripts/2-init-DML.sql /docker-entrypoint-initdb.d/
COPY db_scripts/worldcitiesCSV.csv /docker-entrypoint-initdb.d/